   #                                                  Titanic Exercise 

   ![titanic](https://userscontent2.emaze.com/images/a5f68f37-6349-4065-a1fc-921cbe7401b2/958230111417e36d6b3c67ffd7bc3494.jpeg)
   #### Practise Pandas

First of all, import the needed libraries.

In [1]:
import pandas as pd
import numpy as np

1. Read in filename and call the variable `titanic`
    - Explore the `titanic` dataset using `info`, `dtypes` & `describe`

In [2]:
data = pd.read_csv('data/titanic.csv')
titanic = pd.DataFrame(data)
titanic.info()
print(titanic.dtypes)
titanic.describe()

<class 'pandas.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 14 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   pclass     1309 non-null   int64
 1   survived   1309 non-null   int64
 2   name       1309 non-null   str
 3   sex        1309 non-null   str
 4   age        1046 non-null   float64
 5   sibsp      1309 non-null   int64
 6   parch      1309 non-null   int64
 7   ticket     1309 non-null   str
 8   fare       1308 non-null   float64
 9   cabin      295 non-null    str
 10  embarked   1307 non-null   str
 11  boat       486 non-null    str
 12  body       121 non-null    float64
 13  home.dest  745 non-null    str
dtypes: float64(3), int64(4), str(7)
memory usage: 143.3 KB
pclass         int64
survived       int64
name             str
sex              str
age          float64
sibsp          int64
parch          int64
ticket           str
fare         float64
cabin            str
embarked         str
boat             str
body         float64
home.dest        str
dtype: object

,pclass,survived,age,sibsp,parch,fare,body
count,1309.000000,1309.000000,1046.000000,1309.000000,1309.000000,1308.000000,121.000000
mean,2.294882,0.381971,29.881138,0.498854,0.385027,33.295479,160.809917
std,0.837836,0.486055,14.413493,1.041658,0.865560,51.758668,97.696922
min,1.000000,0.000000,0.170000,0.000000,0.000000,0.000000,1.000000
25%,2.000000,0.000000,21.000000,0.000000,0.000000,7.895800,72.000000
50%,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,155.000000
75%,3.000000,1.000000,39.000000,1.000000,0.000000,31.275000,256.000000
max,3.000000,1.000000,80.000000,8.000000,9.000000,512.329200,328.000000

2. Create a separate dataframe with the columns `['name', 'sex', 'age']`, call it `people`

It can be done two ways, do it both!

In [3]:
people = pd.DataFrame(titanic[['name','sex', 'age']])
people

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

In [4]:
people = titanic.loc[:, ["name", "sex", "age"]]

3. Print the output of `people` showing the first three rows and the last four rows, using `append`,`tail` and `head`

In [5]:
people.head(3)
people.tail(4)
pd.concat([people.head(3), people.tail(4)])

                                name     sex    age
0      Allen, Miss. Elisabeth Walton  female  29.00
1     Allison, Master. Hudson Trevor    male   0.92
2       Allison, Miss. Helen Loraine  female   2.00
1305           Zabour, Miss. Thamine  female    NaN
1306       Zakarian, Mr. Mapriededer    male  26.50
1307             Zakarian, Mr. Ortin    male  27.00
1308              Zimmerman, Mr. Leo    male  29.00

4. Slice the row from 3 to 9, call it `s_titanic`

In [6]:
s_titanic = titanic[3 : 9]
s_titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.0,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
5,1,1,"Anderson, Mr. Harry",male,48.0,0,0,19952,26.5500,E12,S,3,NaN,"New York, NY"
6,1,1,"Andrews, Miss. Kornelia Theodosia",female,63.0,1,0,13502,77.9583,D7,S,10,NaN,"Hudson, NY"
7,1,0,"Andrews, Mr. Thomas Jr",male,39.0,0,0,112050,0.0000,A36,S,NaN,NaN,"Belfast, NI"
8,1,1,"Appleton, Mrs. Edward Dale (Charlotte Lamson)",female,53.0,2,0,11769,51.4792,C101,S,D,NaN,"Bayside, Queens, NY"

5. Slice the row from 40 to 63 in reverse order, call it `s_titanic_rev`

In [7]:
s_titanic_rev = titanic[63 : 40 : -1]
s_titanic_rev

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
63,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S,4,NaN,"Amenia, ND"
62,1,0,"Chaffee, Mr. Herbert Fuller",male,46.0,1,0,W.E.P. 5734,61.1750,E31,S,NaN,NaN,"Amenia, ND"
61,1,1,"Cavendish, Mrs. Tyrell William (Julia Florence...",female,76.0,1,0,19877,78.8500,C46,S,6,NaN,"Little Onn Hall, Staffs"
60,1,0,"Cavendish, Mr. Tyrell William",male,36.0,1,0,19877,78.8500,C46,S,NaN,172.0,"Little Onn Hall, Staffs"
59,1,1,"Cassebeer, Mrs. Henry Arthur Jr (Eleanor Genev...",female,NaN,0,0,17770,27.7208,NaN,C,5,NaN,"New York, NY"
58,1,0,"Case, Mr. Howard Brown",male,49.0,0,0,19924,26.0000,NaN,S,NaN,NaN,"Ascot, Berkshire / Rochester, NY"
57,1,1,"Carter, Mrs. William Ernest (Lucile Polk)",female,36.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
56,1,1,"Carter, Mr. William Ernest",male,36.0,1,2,113760,120.0000,B96 B98,S,C,NaN,"Bryn Mawr, PA"
55,1,1,"Carter, Miss. Lucile Polk",female,14.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
54,1,1,"Carter, Master. William Thornton II",male,11.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
53,1,0,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S,NaN,NaN,"Montevideo, Uruguay"
52,1,0,"Carrau, Mr. Francisco M",male,28.0,0,0,113059,47.1000,NaN,S,NaN,NaN,"Montevideo, Uruguay"
51,1,0,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S,NaN,NaN,"New York, NY"
50,1,1,"Cardeza, Mrs. James Warburton Martinez (Charlo...",female,58.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Germantown, Philadelphia, PA"
49,1,1,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,0,1,PC 17755,512.3292,B51 B53 B55,C,3,NaN,"Austria-Hungary / Germantown, Philadelphia, PA"
48,1,1,"Candee, Mrs. Edward (Helen Churchill Hungerford)",female,53.0,0,0,PC 17606,27.4458,NaN,C,6,NaN,"Washington, DC"
47,1,1,"Calderhead, Mr. Edward Pennington",male,42.0,0,0,PC 17476,26.2875,E24,S,5,NaN,"New York, NY"
46,1,0,"Cairns, Mr. Alexander",male,NaN,0,0,113798,31.0000,NaN,S,NaN,NaN,NaN
45,1,0,"Butt, Major. Archibald Willingham",male,45.0,0,0,113050,26.5500,B38,S,NaN,NaN,"Washington, DC"
44,1,1,"Burns, Miss. Elizabeth Margaret",female,41.0,0,0,16966,134.5000,E40,C,3,NaN,NaN
43,1,1,"Bucknell, Mrs. William Robert (Emma Eliza Ward)",female,60.0,0,0,11813,76.2917,D15,C,8,NaN,"Philadelphia, PA"
42,1,1,"Brown, Mrs. John Murray (Caroline Lane Lamson)",female,59.0,2,0,11769,51.4792,C101,S,D,NaN,"Belmont, MA"
41,1,1,"Brown, Mrs. James Joseph (Margaret Tobin)",female,44.0,0,0,PC 17610,27.7208,B4,C,6,NaN,"Denver, CO"

6. Slice the columns from the starting column to `'parch'`, call it `left_columns`

In [8]:
left_columns = titanic.loc[ : , : 'parch']
left_columns

,pclass,survived,name,sex,age,sibsp,parch
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2
...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0

7. Slice the columns from `'name'` to `'age'`, call it `middle_columns`

In [9]:
middle_columns = titanic.loc[ : , 'name' : 'age' ]
middle_columns

                                                 name     sex    age
0                       Allen, Miss. Elisabeth Walton  female  29.00
1                      Allison, Master. Hudson Trevor    male   0.92
2                        Allison, Miss. Helen Loraine  female   2.00
3                Allison, Mr. Hudson Joshua Creighton    male  30.00
4     Allison, Mrs. Hudson J C (Bessie Waldo Daniels)  female  25.00
...                                               ...     ...    ...
1304                             Zabour, Miss. Hileni  female  14.50
1305                            Zabour, Miss. Thamine  female    NaN
1306                        Zakarian, Mr. Mapriededer    male  26.50
1307                              Zakarian, Mr. Ortin    male  27.00
1308                               Zimmerman, Mr. Leo    male  29.00

[1309 rows x 3 columns]

8. Slice the columns from `'ticket'` to the end, call it `right_columns`

In [10]:
right_columns = titanic.loc[ : , 'ticket' :  ]
right_columns
titanic

,pclass,survived,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

9. What is the name of the oldest person who died in the Titanic? Was he or she travelling alone or had any family travelling with them?

In order to give an answer to the second question you should find out which columns give you that info. Usually part of your job as a Data Scientist will be get to know the dataset which you are working with. In this case the columns which give you that info are the following: 
        - 'sibsp' Number of Siblings/Spouses Aboard
        - 'parch' Number of Parents/Children Aboard

In [11]:
muertos = titanic.query('survived == 0')
fila = muertos['age'].idxmax()
muertos.loc[fila, ['name', 'age', 'sibsp', 'parch']]

name     Svensson, Mr. Johan
age                     74.0
sibsp                      0
parch                      0
Name: 1235, dtype: object

In [12]:
vivos = titanic.query('survived == 1')
fila = titanic['age'].idxmin()
titanic.loc[fila, ['name', 'age', 'pclass', 'parch']]

name      Dean, Miss. Elizabeth Gladys "Millvina"
age                                          0.17
pclass                                          3
parch                                           2
Name: 763, dtype: object

10. Create the list of 5 random numbers of rows from 0 to the lenght of the dataframe, call it `rows`

ex. `rows = [3,7,99,52,48]` use `random` library

This list of numbers are random, could be different.

In [13]:
import random as r

In [14]:
rows = []
for i in range(5):
    rows.append(r.randint(0, len(titanic)))
rows

[293, 1274, 1076, 562, 597]

11. Create the list of three column labels, call it `cols`

In [15]:
cols = ['name', 'age', 'sex']
cols

['name', 'age', 'sex']

12. Use both lists `rows` and `cols` to create a new dataframe

In [16]:
new_dataframe = titanic.loc[rows, cols]
new_dataframe

                                                   name   age     sex
293   Taylor, Mrs. Elmer Zebley (Juliet Cummins Wright)   NaN  female
1274                          Vander Planke, Mr. Julius  31.0    male
1076                            O'Donoghue, Ms. Bridget   NaN  female
562                           Slayter, Miss. Hilda Mary  30.0  female
597                        Williams, Mr. Charles Eugene   NaN    male

13. Create a boolean array with the condition of being a woman or a man, using the `sex` column, where **female** is True. Call it `array_fe`

In [17]:
array_fe = titanic['sex'] == 'female'

14. Rename the column `"sex"` to `"gender"` and filter the `titanic` dataframe with the boolean array, call it `woman_titanic`

In [18]:
titanic = titanic.rename(columns={'sex' : 'gender'})
titanic

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
0,1,1,"Allen, Miss. Elisabeth Walton",female,29.00,0,0,24160,211.3375,B5,S,2,NaN,"St Louis, MO"
1,1,1,"Allison, Master. Hudson Trevor",male,0.92,1,2,113781,151.5500,C22 C26,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1,0,"Allison, Miss. Helen Loraine",female,2.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1,0,"Allison, Mr. Hudson Joshua Creighton",male,30.00,1,2,113781,151.5500,C22 C26,S,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1,0,"Allison, Mrs. Hudson J C (Bessie Waldo Daniels)",female,25.00,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1304,3,0,"Zabour, Miss. Hileni",female,14.50,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN
1305,3,0,"Zabour, Miss. Thamine",female,NaN,1,0,2665,14.4542,NaN,C,NaN,NaN,NaN
1306,3,0,"Zakarian, Mr. Mapriededer",male,26.50,0,0,2656,7.2250,NaN,C,NaN,304.0,NaN
1307,3,0,"Zakarian, Mr. Ortin",male,27.00,0,0,2670,7.2250,NaN,C,NaN,NaN,NaN
1308,3,0,"Zimmerman, Mr. Leo",male,29.00,0,0,315082,7.8750,NaN,S,NaN,NaN,NaN

15. How many woman were younger than 18? Call the variable `minor_wo`

In [19]:
femmes = titanic.query('gender == "female"')
minor_wo = femmes.query('age < 18')
minor_wo

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
2,1,0,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
55,1,1,"Carter, Miss. Lucile Polk",female,14.0,1,2,113760,120.0000,B96 B98,S,4,NaN,"Bryn Mawr, PA"
92,1,1,"Dick, Mrs. Albert Adrian (Vera Gillespie)",female,17.0,1,0,17474,57.0000,B20,S,3,NaN,"Calgary, AB"
159,1,1,"Hippach, Miss. Jean Gertrude",female,16.0,0,1,111361,57.9792,B18,C,4,NaN,"Chicago, IL"
187,1,1,"Lines, Miss. Mary Conover",female,16.0,0,1,PC 17592,39.4000,D28,S,9,NaN,"Paris, France"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1257,3,1,"Touma, Miss. Maria Youssef",female,9.0,1,1,2650,15.2458,NaN,C,C,NaN,NaN
1265,3,0,"Van Impe, Miss. Catharina",female,10.0,0,2,345773,24.1500,NaN,S,NaN,NaN,NaN
1279,3,0,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,NaN,NaN,NaN
1300,3,1,"Yasbeck, Mrs. Antoni (Selini Alexander)",female,15.0,1,0,2659,14.4542,NaN,C,NaN,NaN,NaN
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN

16. How many woman that were less than 18 actually died? Call the variable `dead_wo`

In [20]:
dead_wo = titanic.query('gender == "female" and age < 18 and survived == 0')
dead_wo

,pclass,survived,name,gender,age,sibsp,parch,ticket,fare,cabin,embarked,boat,body,home.dest
2,1,0,"Allison, Miss. Helen Loraine",female,2.0,1,2,113781,151.5500,C22 C26,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"
623,3,0,"Andersson, Miss. Ebba Iris Alfrida",female,6.0,4,2,347082,31.2750,NaN,S,NaN,NaN,"Sweden Winnipeg, MN"
624,3,0,"Andersson, Miss. Ellis Anna Maria",female,2.0,4,2,347082,31.2750,NaN,S,NaN,NaN,"Sweden Winnipeg, MN"
627,3,0,"Andersson, Miss. Ingeborg Constanzia",female,9.0,4,2,347082,31.2750,NaN,S,NaN,NaN,"Sweden Winnipeg, MN"
628,3,0,"Andersson, Miss. Sigrid Elisabeth",female,11.0,4,2,347082,31.2750,NaN,S,NaN,NaN,"Sweden Winnipeg, MN"
650,3,0,"Attalah, Miss. Malake",female,17.0,0,0,2627,14.4583,NaN,C,NaN,NaN,NaN
679,3,0,"Boulos, Miss. Nourelain",female,9.0,1,1,2678,15.2458,NaN,C,NaN,NaN,"Syria Kent, ON"
807,3,0,"Ford, Miss. Robina Maggie ""Ruby""",female,9.0,2,2,W./C. 6608,34.3750,NaN,S,NaN,NaN,"Rotherfield, Sussex, England Essex Co, MA"
828,3,0,"Goodwin, Miss. Jessie Allis",female,10.0,5,2,CA 2144,46.9000,NaN,S,NaN,NaN,"Wiltshire, England Niagara Falls, NY"
829,3,0,"Goodwin, Miss. Lillian Amy",female,16.0,5,2,CA 2144,46.9000,NaN,S,NaN,NaN,"Wiltshire, England Niagara Falls, NY"
841,3,0,"Hagardon, Miss. Kate",female,17.0,0,0,AQ/3. 30631,7.7333,NaN,Q,NaN,NaN,NaN
937,3,0,"Klasen, Miss. Gertrud Emilia",female,1.0,1,1,350405,12.1833,NaN,S,NaN,NaN,NaN
1098,3,0,"Palsson, Miss. Stina Viola",female,3.0,3,1,349909,21.0750,NaN,S,NaN,NaN,NaN
1099,3,0,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S,NaN,NaN,NaN
1112,3,0,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S,NaN,NaN,NaN
1156,3,0,"Rosblom, Miss. Salli Helena",female,2.0,1,1,370129,20.2125,NaN,S,NaN,NaN,NaN
1208,3,0,"Skoog, Miss. Mabel",female,9.0,3,2,347088,27.9000,NaN,S,NaN,NaN,NaN
1209,3,0,"Skoog, Miss. Margit Elizabeth",female,2.0,3,2,347088,27.9000,NaN,S,NaN,NaN,NaN
1230,3,0,"Strom, Miss. Telma Matilda",female,2.0,0,1,347054,10.4625,G6,S,NaN,NaN,NaN
1265,3,0,"Van Impe, Miss. Catharina",female,10.0,0,2,345773,24.1500,NaN,S,NaN,NaN,NaN
1279,3,0,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S,NaN,NaN,NaN
1304,3,0,"Zabour, Miss. Hileni",female,14.5,1,0,2665,14.4542,NaN,C,NaN,328.0,NaN

17. Drop rows with *Nan* in `titanic` with `how='any'` and print the shape

In [21]:
titanic.dropna(how='any').shape

(0, 14)

18. Drop rows with *Nan* in `titanic` with `how='all'` and print the shape

In [22]:
titanic.dropna(how="all").shape

(1309, 14)

Check in [here](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.dropna.html) why the shapes are different.

19. Drop columns in `titanic` with more than 1000 missing values and print the columns remaining

In [23]:
vacias = titanic.isna().sum()
masmil = vacias[vacias > 1000].index
titanic = titanic.drop(columns=masmil)

20. Calculate the ratio of missing values at the `boat` column.

In [24]:
valor = titanic['boat'].isna().sum() / len(titanic)
valor

np.float64(0.6287242169595111)

21.  Group `titanic` by `'pclass'` and aggregate by the columns `age` & `fare`, by `max` and `median` and assign it to `by_class`

In [25]:
by_class = titanic.groupby('pclass')[['age', 'fare']].aggregate(['max', 'median'])
by_class

         age             fare
         max median       max   median
pclass
1       80.0   39.0  512.3292  60.0000
2       70.0   29.0   73.5000  15.0458
3       74.0   24.0   69.5500   8.0500

22. Print the maximum age in each class from `by_class`

In [26]:
by_class['age']['max']

pclass
1    80.0
2    70.0
3    74.0
Name: max, dtype: float64

23. Print the median fare in each class from `by_class`

In [27]:
by_class['fare']['median']

pclass
1    60.0000
2    15.0458
3     8.0500
Name: median, dtype: float64

24. Using [`.pivot_table()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.pivot_table.html) to count how many women or men survived by class, call it `counted`.

Don't panic and read the documentation!

In [28]:
counted = titanic.pivot_table(values='survived', index="gender", columns="pclass", aggfunc='sum')
counted = titanic.pivot_table(values="survived", index="pclass", columns="gender", aggfunc="sum")
counted

gender  female  male
pclass
1          139    61
2           94    25
3          106    75

25. Add a new column with the sum of survived men and women, call it `counted['total']`

In [29]:
counted["total"] = counted["female"] + counted["male"]
counted

gender  female  male  total
pclass
1          139    61    200
2           94    25    119
3          106    75    181

26. Sort `counted` by the `'total'` column. In which class the people survived the most?

In [30]:
counted.sort_values(by="total", ascending=False)

gender  female  male  total
pclass
1          139    61    200
3          106    75    181
2           94    25    119

27. Please, show only the rows using a mask with the following conditions: 
    - They are woman
    - From third class
    - Younger than 30
    - They survived
    
    ¿How many rows fulfill the condition?

In [31]:
mask = (
    (titanic['gender'] == 'female')
    & (titanic['pclass'] == 3)
    & (titanic['age'] < 30)
    & (titanic['survived'] == 1)
)
mask.sum()

np.int64(57)

28. Now, show only the rows using `.loc` with the following conditions: 
    - They are man
    - From first class
    - Older than 50
    - They died
    
    ¿How many rows fulfill the condition?

In [33]:
mask_2 = titanic.loc[
    (titanic['gender'] == 'male')
    & (titanic['pclass'] == 1)
    & (titanic['age'] > 50)
    & (titanic['survived'] == 0)
]

mask_2.sum()

pclass                                                      29
survived                                                     0
name         Artagaveytia, Mr. RamonCrosby, Capt. Edward Gi...
gender       malemalemalemalemalemalemalemalemalemalemalema...
age                                                     1741.0
sibsp                                                       10
parch                                                       16
ticket       PC 17609WE/P 573519950PC 177541274968011771174...
fare                                                 2252.7501
embarked                         CSSCSSCSSSCSCCCSCCSSSSSCSSSCS
boat                                                         0
home.dest    Montevideo, UruguayMilwaukee, WIWinnipeg, MBNe...
dtype: object

29. Print the uniques values at the column `'name'`

In [ ]:
titanic['name'].nunique()

1307

30. Find if was there any `name` repeated at the Titanic?

Hint: There were two people with the same name, who?

31. Using `matplotlib` find the appropriate visualization to show the distribution of the column `'age'`

In [ ]:
import matplotlib.pyplot as plt

32. Using `matplotlib` find the appropriate plot to visualize the column `'gender'`

32b. What if you also plot the column `'gender'` using the function [`countplot`](https://seaborn.pydata.org/generated/seaborn.countplot.html) from the library [`seaborn`](https://seaborn.pydata.org/)?

Remember you have never used `seaborn` before, therefore you should install it before importing it.

In [ ]:
import seaborn as sns

33. Using the function [`catplot`](https://seaborn.pydata.org/generated/seaborn.catplot.html) from the library `seaborn`, find out if the hypothesis _"Women are more likely to survive shipwrecks"_ is true or not.

You should get something like this:

![catplot](./img/catplotgen.png)

34. Using [`kdeplot`]("https://seaborn.pydata.org/generated/seaborn.kdeplot.html") from `seaborn` represent those who not survived distributed by age.<>

Hint: First you should "filter" the `titanic` dataset where the column "survived" is 0, indexing the column `"age"` only.

Arguments you should pass to the function: 

    - color = "red"
    - label = "Not Survived"
    - shade = True
    
You should get something like this:

![kdeplot](./img/kdeplotsur.png)